<?php

namespace ContainerVET7V31;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GeAM7WXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GeAM7WX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GeAM7WX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminJobController::delete' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\AdminJobController::edit' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator._r0oHHG', 'get_ServiceLocator_R0oHHGService', true],
            'App\\Controller\\OfferController::index' => ['privates', '.service_locator.tNQRXAp', 'get_ServiceLocator_TNQRXApService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminJobController:delete' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\AdminJobController:edit' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator._r0oHHG', 'get_ServiceLocator_R0oHHGService', true],
            'App\\Controller\\OfferController:index' => ['privates', '.service_locator.tNQRXAp', 'get_ServiceLocator_TNQRXApService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminJobController::delete' => '?',
            'App\\Controller\\AdminJobController::edit' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\OfferController::index' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminJobController:delete' => '?',
            'App\\Controller\\AdminJobController:edit' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\OfferController:index' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
