<?php

namespace ContainerVET7V31;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterStudyFieldTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FilterStudyFieldType' shared autowired service.
     *
     * @return \App\Form\FilterStudyFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FilterStudyFieldType.php';

        return $container->privates['App\\Form\\FilterStudyFieldType'] = new \App\Form\FilterStudyFieldType();
    }
}
