<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_fortawesome_fontawesome-free_js_all_js-node_modules_symfony_stimulus-bri-0a270f.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_fortawesome_fontawesome-free_js_all_js-node_modules_symfony_stimulus-bri-0a270f.css',
                '/build/app.css',
            ],
        ],
        'adminJob' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/adminJob.css',
            ],
        ],
        'home' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/home.css',
            ],
        ],
        'navbar' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/navbar.css',
            ],
        ],
        'profile' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/profile.css',
            ],
        ],
    ],
],

]];
